version: '3.1'

services:
  db:
    image: postgres:13.5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: software_anotacao
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  sox:
    image: ubuntu
    restart: always
    container_name: sox-container
    command: >
      sh -c "apt-get update -y 
      && apt-get install -y sox libsox-fmt-mp3
      && tail -f /dev/null"
    working_dir: /files
    volumes:
      - ./public/files:/files
    ports:
      - 508:508

  annotation_service:
    image: python:3.8
    restart: always
    container_name: annotation_service
    working_dir: /code
    volumes:
      - ./annotation_service:/code
    command: >
      sh -c "pip install -r ./requirements.txt
      && python -m nltk.downloader stopwords
      && python3.8 ./controladorActiveLearning.py
      && tail -f /dev/null"
    ports:
      - 9099:9099